name: Build docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #build service    
    - name: Build servuce
      run: |
        npm install
        npm run build
      working-directory: ./service

    #publish images      
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push oidp image
      uses: docker/build-push-action@v4
      with:
        context: ./service
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/aczwink/opendistributedfilestorage:latest
